library(usethis)
use_git()
use_github()
use_mit_license()
use_readme_rmd()
use_testthat()
use_spell_check()
use_r("fishing")
use_package("magrittr")
use_package("dplyr")
use_package("jsonlite")
use_package("git2r")

use_package("httr")
